FROM 4pdosc/openembedding-base:0.1.0

# only c api is tested here
ADD . /openembedding
ARG VERSION=0.0.0
RUN pip3 install pybind11
RUN PATH=/dt7/usr/bin:$PATH prefix=/tools /openembedding/pico-ps/pico-core/third_party/prepare.sh build eigen
RUN cd /openembedding && \
    PATH=/dt7/usr/bin:$PATH SKIP_CHECK_WHEEL_SETUP=1 VERSION=${VERSION} THIRD_PARTY=/tools ./build.sh
RUN cd /openembedding/build && make test
