# 主要是为了使用里面的 glibc 2.12 和 dt7，和 tensorflow 具有相同的系统兼容性
FROM tensorflow/tensorflow:2.3.0-custom-op-ubuntu16

RUN cd /dt7/usr/bin && ln -s gcc cc && cd /

# use glibc 2.12
ADD pico-ps/pico-core/third_party /third_party

RUN third_party/prepare.sh build cmake
RUN PATH=/dt7/usr/bin:$PATH prefix=/tools third_party/prepare.sh build \
    gflags glog googletest sparsehash zlib snappy lz4 boost yaml jemalloc prometheus-cpp \
    avro-cpp zookeeper protobuf leveldb openssl brpc && cd ..
