name: build

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: docker build
        run: |
          docker/docker_build.sh
      - name: docker image
        run: |
          docker/docker_build.sh image
      - name: docker test
        run: |
          docker/docker_build.sh test
