name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build
        run: |
          VERSION=${BRANCH_NAME:1} docker/docker_build.sh
      - name: docker image
        run: |
          VERSION=${BRANCH_NAME:1} docker/docker_build.sh image
      - name: docker test
        run: |
          VERSION=${BRANCH_NAME:1} docker/docker_build.sh test
      - name: docker push
        run: |
          docker push 4pdosc/openembedding:${BRANCH_NAME:1}
          docker tag 4pdosc/openembedding:${BRANCH_NAME:1} 4pdosc/openembedding:latest
          docker push 4pdosc/openembedding:latest
      - name: pypi upload
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip3 install twine
          twine upload output/dist/openembedding-${BRANCH_NAME:1}.tar.gz
